version: '3.9'
services:
    nginx:
        depends_on:
            - wordpress
        build: ./nginx2
        container_name: nginx
        volumes:
            - wp:/var/www/wordpress
        ports:
            - '443:443'
        networks:
            - web
    mariadb:
        container_name: mariadb
        build: ./mariadb
        restart: on-failure
        env_file: .env
        volumes:
            - db:/var/lib/mysql
        networks:
            - web
    wordpress:
        depends_on:
            - mariadb
        build: ./wordpress
        container_name: wordpress
        restart: always
        volumes:
            - wp:/var/www/wordpress
        expose:
            - '9000:9000'
        env_file:
            - .env
        # volumes:
        #     - ${PWD}/wordpress:/var/www/html
        networks:
            - web
volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db


networks:
  web:
    driver: bridge
    # mariadb:
    #     image: mariadb:10.3.9
    #     container_name: ${APP_NAME:?err}-mariadb
    #     restart: 'on-failure'
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    #     volumes:
            # - ${PWD}

