version: '3.9'
services:
    nginx:
        depends_on:
            - wordpress
        build: ./nginx
        container_name: nginx
        ports:
            - '443:443'
        networks:
            - web
    wordpress:
        depends_on:
            - mariadb
        build: ./wordpress
        container_name: wordpress
        restart: always
        expose:
            - '9000:9000'
        # volumes:
        #     - ${PWD}/wordpress:/var/www/html
        networks:
            - web
    mariadb:
        build: ./mariadb
        container_name: mariadb
        restart: always

        # image: mariadb:10.3.9
        # container_name: mariadb
        # restart: 'on-failure'
        # environment:
        #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        # volumes:
        #     - ${PWD}/mariadb:/var/lib/mysql
        networks:
            - web

networks:
  web:
    driver: bridge
    # mariadb:
    #     image: mariadb:10.3.9
    #     container_name: ${APP_NAME:?err}-mariadb
    #     restart: 'on-failure'
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    #     volumes:
            # - ${PWD}